maker: login.cpp mainUI.cpp customer.cpp userTest.cpp account.cpp
		g++ -I ../include/ login.cpp mainUI.cpp -l sqlite3 -o login
		g++ -I ../include/ customer.cpp userTest.cpp account.cpp -l sqlite3 -o userTest